import {freshJourney,validateJourney,advanceJourney,journeyComplete,judgeSteps} from '../../packages/games/judge-journey.mjs';
import {QueueLineRun} from '../../packages/games/queue-line.mjs';
import {validateCall,gradeResponse} from '../../packages/games/call-response.mjs';
import {createDevice,signOffer,acceptOffer,inspectPacket} from '../../packages/protocol/swap.mjs';
import {initialAllocation,allocate} from '../../packages/protocol/allocator.mjs';
import {prepareOffline} from './offline.mjs';
import {renderPictureBoard} from './picture-board.mjs';
const $=s=>document.querySelector(s),key='tonari-judge-journey-v1',hex=n=>n.toString(16).padStart(2,'0').repeat(32);
let state=(()=>{try{return validateJourney(JSON.parse(localStorage.getItem(key)));}catch{return freshJourney();}})();
function render(){localStorage.setItem(key,JSON.stringify(state));$('#tile-count').textContent=String(state.tiles);const owned=Array.from({length:state.tiles},(_,i)=>i),view=renderPictureBoard($('#board'),owned,Array.from({length:24},(_,i)=>i),'i');for(const [i,step] of judgeSteps.entries()){const card=document.querySelector(`[data-step="${step}"]`);card.classList.toggle('done',i<state.completed.length);card.classList.toggle('active',i===state.completed.length);}if(journeyComplete(state)&&view.complete){document.querySelector('tonari-guide').setAttribute('state','complete');$('#complete').hidden=false;$('#picture-reveal').hidden=false;$('#journey-status').textContent='全6体験が完了しました。24枚が一枚の記念絵になりました。';}else{$('#complete').hidden=true;$('#picture-reveal').hidden=true;$('#journey-status').textContent=`${state.completed.length+1} / 6　次のカードを体験してください。`;}}
function finish(step,proof){if(state.completed.includes(step))return;state=advanceJourney(state,step,proof===true);render();document.querySelector(`[data-step="${judgeSteps[state.completed.length]}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});}
$('#verify-swap').addEventListener('click',async()=>{try{const [a,b]=await Promise.all([createDevice(),createDevice()]),offer={show:hex(1),a:a.publicKey,b:b.publicKey,tileA:hex(2),tileB:hex(3),nonce:'04'.repeat(16),issuedAt:1000,expiresAt:1120},signed=await signOffer(a,offer),packet=await acceptOffer(b,signed,{show:offer.show,now:1001}),proof=await inspectPacket(packet,{show:offer.show,now:1001});$('#swap-proof').textContent=`✓ 2署名を検証・${proof.id.slice(0,12)}…・所有権は確定前`;finish('swap',proof.status==='PROVISIONAL'&&proof.ownershipFinal===false);}catch(error){$('#swap-proof').textContent='確認に失敗しました：'+error.message;}});
const queueSolution=[0,1,2,3,7,6,5,4,8,9,10,11,15,14,13,12],queue=new QueueLineRun({id:'judge-queue',size:4,clues:[{cell:0,number:1},{cell:7,number:2},{cell:8,number:3},{cell:15,number:4},{cell:12,number:5}]});for(let cell=0;cell<16;cell++){const button=document.createElement('button');button.dataset.cell=String(cell);button.textContent=queue.puzzle.clues.get(cell)||'·';button.addEventListener('click',()=>{if(state.completed.length!==1)return;const moved=queue.move(cell);if(moved.changed)button.classList.add('path');if(queue.solved){$('#queue-proof').textContent='✓ 16 / 16　ゴーストより先に列がつながりました';finish('queue',true);}else if(!moved.changed)$('#queue-proof').textContent='上下左右へ、薄い順路を進んでください。';});$('#mini-queue').append(button);}for(const [i,cell] of queueSolution.entries())document.querySelector(`[data-cell="${cell}"]`).style.setProperty('--order',String(i));
const call=validateCall({id:'judge-call',bpm:100,pads:[0,1,2]}),answer=[];$('#show-call').addEventListener('click',()=>{if(state.completed.length!==2)return;answer.length=0;$('#call-proof').textContent='●　▲　■　を同じ順番で返してください。';});for(const button of document.querySelectorAll('[data-call-pad]'))button.addEventListener('click',()=>{if(state.completed.length!==2)return;answer.push(Number(button.dataset.callPad));if(answer.length===call.pads.length){const taps=answer.map((pad,i)=>({pad,at:i*call.stepMs})),grade=gradeResponse(call,taps);$('#call-proof').textContent=grade.fullCombo?'✓ フルコンボ・厳格な採点核を通過':'順番が違います。コールを見てもう一度。';if(grade.fullCombo)finish('call',true);else answer.length=0;}});
$('#run-allocator').addEventListener('click',()=>{if(state.completed.length!==3)return;const result=allocate(initialAllocation(),{waits:[8,7,6,5,1,7,8,6],spotGiven:[0,0,0,0,0,0,0,0],boundary:true,nudge:2,budget:24,given:7}),best=result.suggestions.indexOf(Math.max(...result.suggestions));$('#rare-proof').textContent=`✓ 静かなスポット ${best+1} を候補に選択・混雑地点は除外`;finish('rare',best===4&&result.capLeft[best]===true);});
$('#accept-offer').addEventListener('click',()=>{if(state.completed.length!==4)return;$('#offer-proof').textContent='✓ 仮想列 10分後・現地で待つ必要はありません';finish('offer',true);});$('#decline-offer').addEventListener('click',()=>{if(state.completed.length===4)$('#offer-proof').textContent='見送っても失うものはありません。予約する場合だけ次へ進みます。';});
$('#confirm-proof').addEventListener('click',()=>{if(state.completed.length!==5)return;$('#chain-proof').textContent='✓ 公開プログラムと確定済み交換取引を分離して表示';finish('proof',true);});
$('#restart').addEventListener('click',()=>{localStorage.removeItem(key);location.reload();});
render();prepareOffline().then(()=>{$('#offline-status').textContent='この審査ルートは通信なしで開き直せます（Explorerリンクを除く）。';document.documentElement.dataset.offlineReady='true';}).catch(error=>{$('#offline-status').textContent='オフライン準備に失敗しました：'+error.message;});
