import {QueueLineRun,validateGhost,ghostAt} from '../../packages/games/queue-line.mjs';
import {prepareOffline} from './offline.mjs';
const $=s=>document.querySelector(s),solution=[0,1,2,3,4,9,8,7,6,5,10,11,12,13,14,19,18,17,16,15,20,21,22,23,24];
const puzzle={id:'chapter-1-small',size:5,clues:[{cell:0,number:1},{cell:9,number:2},{cell:10,number:3},{cell:14,number:4},{cell:20,number:5},{cell:24,number:6}]},ghost=validateGhost(puzzle,{path:solution,times:solution.map((_,i)=>(i+1)*900)}),run=new QueueLineRun(puzzle);
let drawing=false,paused=false,started=0,pausedAt=0,pausedTotal=0,frame=0;
for(let cell=0;cell<25;cell++){const button=document.createElement('button'),clue=run.puzzle.clues.get(cell);button.className='queue-cell'+(clue?' clue':'');button.dataset.cell=String(cell);button.setAttribute('role','gridcell');button.textContent=clue||'';button.addEventListener('pointerdown',event=>{event.preventDefault();drawing=true;move(cell);});button.addEventListener('pointerenter',event=>{if(drawing&&event.buttons)move(cell);});$('#queue-grid').append(button);}
addEventListener('pointerup',()=>drawing=false);
const elapsed=()=>started?performance.now()-started-pausedTotal-(paused?performance.now()-pausedAt:0):0;
function move(cell){if(paused||run.solved)return;if(!started){started=performance.now();tick();}const result=run.move(cell);if(result.changed)render();else{$('#queue-status').textContent='上下左右へ、次の番号より先に進まないようにつなぎます。';}}
function render(){for(const node of document.querySelectorAll('.queue-cell')){const cell=Number(node.dataset.cell),at=run.path.indexOf(cell);node.classList.toggle('path',at>=0);node.classList.toggle('head',at===run.path.length-1);node.classList.remove('ghost');}if(run.solved){document.body.classList.add('solved');$('#queue-status').textContent='列がつながりました ✓　絵があらわれた。もう一回は練習です。';document.querySelector('tonari-guide').setAttribute('state','complete');cancelAnimationFrame(frame);}}
function tick(){const ms=elapsed(),g=ghostAt(ghost,ms);$('#time').textContent=(ms/1000).toFixed(1)+'秒';for(const node of document.querySelectorAll('.queue-cell'))node.classList.toggle('ghost',g?.cell===Number(node.dataset.cell));if(!run.solved)frame=requestAnimationFrame(tick);}
function reset(){cancelAnimationFrame(frame);run.reset();started=0;paused=false;pausedAt=0;pausedTotal=0;document.body.classList.remove('solved');$('#queue-grid').classList.remove('paused');$('#pause').textContent='一時停止';$('#time').textContent='0.0秒';$('#queue-status').textContent='1から指でなぞってください。';document.querySelector('tonari-guide').setAttribute('state','waiting');render();}
$('#undo').addEventListener('click',()=>{if(!paused&&run.undo())render();});$('#retry').addEventListener('click',reset);$('#pause').addEventListener('click',()=>{if(!started||run.solved)return;paused=!paused;if(paused)pausedAt=performance.now();else{pausedTotal+=performance.now()-pausedAt;frame=requestAnimationFrame(tick);}$('#queue-grid').classList.toggle('paused',paused);$('#pause').textContent=paused?'続ける':'一時停止';$('#queue-status').textContent=paused?'列が動いたら、そのまま閉じても大丈夫です。':'続きからどうぞ。';if(paused)cancelAnimationFrame(frame);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&started&&!run.solved)$('#pause').click();});
prepareOffline().then(()=>{$('#offline-status').textContent='通信なしで開き直して、練習を続けられます。';document.documentElement.dataset.offlineReady='true';}).catch(error=>{$('#offline-status').textContent='通信なしでの再起動は準備できませんでした：'+error.message;});
