import test from 'node:test';
import assert from 'node:assert/strict';
import {validateCall,gradeResponse,makeSoloCall,calibrationOffset} from '../packages/games/call-response.mjs';

const call={id:'solo-one',bpm:120,pads:[0,1,2,null,3]};
test('Call & Response grades calibrated pad timing at forgiving exact boundaries',()=>{const taps=[{pad:0,at:50},{pad:1,at:320},{pad:2,at:630},{pad:3,at:1050}];const result=gradeResponse(call,taps,50);assert.deepEqual(result.grades.map(x=>x.grade),['BEST','BEST','GOOD','BEST']);assert.equal(result.accuracy,100);assert.equal(result.fullCombo,true);});
test('wrong, late, missing and extra pads are honest misses',()=>{const result=gradeResponse(call,[{pad:1,at:0},{pad:1,at:451},{pad:2,at:500},{pad:3,at:1000},{pad:0,at:1200}]);assert.equal(result.misses,3);assert.equal(result.fullCombo,false);assert.equal(result.accuracy,40);});
test('solo bot grows from two pads and three beats without exceeding twelve beats or 140 BPM',()=>{assert.deepEqual(makeSoloCall(1,9).pads.length,3);assert.equal(Math.max(...makeSoloCall(2,9).pads),1);assert.ok(Math.max(...makeSoloCall(3,9).pads)<=2);assert.ok(Math.max(...makeSoloCall(5,9).pads)<=3);assert.equal(makeSoloCall(100,9).pads.length,12);assert.equal(makeSoloCall(100,9).bpm,140);assert.deepEqual(makeSoloCall(7,44),makeSoloCall(7,44));});
test('solo bot output is directly gradeable without losing its validated timing',()=>{const generated=makeSoloCall(1,9),taps=generated.pads.map((pad,index)=>({pad,at:index*generated.stepMs})),result=gradeResponse(generated,taps);assert.equal(result.fullCombo,true);assert.equal(result.accuracy,100);assert.equal(result.hits,generated.pads.length);});
test('call schema and response evidence reject ambiguity',()=>{for(const bad of [{...call,extra:1},{...call,bpm:99},{...call,pads:[0,1]},{...call,pads:[0,4,1]},{...call,pads:[null,null,null]}])assert.throws(()=>validateCall(bad));assert.throws(()=>gradeResponse({...makeSoloCall(1,9),stepMs:1},[]));assert.throws(()=>gradeResponse(call,[{pad:0,at:10},{pad:1,at:10}]));assert.throws(()=>gradeResponse(call,[{pad:0,at:10,extra:true}]));});
test('eight-tap calibration uses a bounded median and rejects incomplete samples',()=>{const samples=[10,12,9,11,400,8,10,12].map((delta,index)=>({expected:index*600,actual:index*600+delta}));assert.equal(calibrationOffset(samples),11);assert.equal(calibrationOffset(samples.map((x,index)=>({...x,actual:x.expected+(index<4?-500:500)}))),0);assert.throws(()=>calibrationOffset(samples.slice(1)));});
