import test from 'node:test';
import assert from 'node:assert/strict';
import {Keypair,PublicKey} from '@solana/web3.js';
import {PROGRAM_ID,showAddress,policyHash,pairAddress,nonceAddress,settlementInstructions,transaction,serializedSize,discriminator,readAccount} from '../tools/chain-client.mjs';
import {encodeOffer,acceptanceMessage} from '../packages/protocol/swap-v2.mjs';
import {concat,hex} from '../packages/protocol/swap.mjs';
async function fixture(){const [a,b,payer]=[Keypair.generate(),Keypair.generate(),Keypair.generate()];const show=showAddress(Buffer.alloc(32,9));const deadline=2000,nonce=Buffer.alloc(16,7);
 const o={show:hex(show.toBytes()),a:hex(a.publicKey.toBytes()),b:hex(b.publicKey.toBytes()),tileA:hex(Buffer.alloc(32,1)),tileB:hex(Buffer.alloc(32,2)),nonce:hex(nonce),issuedAt:1000,expiresAt:1120,policy:hex(policyHash(show,deadline,24)),versionA:0,versionB:0,settleBy:deadline,reserved:0};
 const body=encodeOffer(o),sa=Buffer.alloc(64,3),sb=Buffer.alloc(64,4);return {a,b,payer,show,nonce,o,packet:concat(body,sa,sb)};}
test('real legacy transaction fits 1232 bytes with sponsor as only signer',async()=>{const f=await fixture(),ix=await settlementInstructions(f.payer.publicKey,f.packet);const tx=transaction(f.payer.publicKey,PublicKey.default.toBase58(),ix);assert.equal(serializedSize(tx),1113);assert.equal(tx.compileMessage().header.numRequiredSignatures,1);assert.equal(ix[2].data.length,24);assert.equal(ix[0].data.length,352);assert.equal(ix[1].data.length,230);assert.equal(ix[2].data.subarray(8).toString('hex'),hex(f.nonce));});
test('pair PDA is order independent; nonce and show namespaces differ',async()=>{const f=await fixture();assert(pairAddress(f.show,f.a.publicKey,f.b.publicKey).equals(pairAddress(f.show,f.b.publicKey,f.a.publicKey)));assert(!pairAddress(f.show,f.a.publicKey,f.b.publicKey).equals(nonceAddress(f.show,f.nonce)));assert(!nonceAddress(f.show,f.nonce).equals(nonceAddress(showAddress(Buffer.alloc(32,8)),f.nonce)));});
test('policy commits actual show and enforcement parameters',async()=>{const f=await fixture();assert.notDeepEqual(policyHash(f.show,2000,24),policyHash(f.show,2001,24));assert.notDeepEqual(policyHash(f.show,2000,24),policyHash(f.show,2000,23));assert.notDeepEqual(policyHash(f.show,2000,24),policyHash(PublicKey.default,2000,24));});
test('account reader rejects wrong program/discriminator/length',()=>{const data=Buffer.alloc(109);discriminator('account','Tile').copy(data);const info={owner:PROGRAM_ID,data};assert.equal(readAccount(info,'Tile').version,0);assert.throws(()=>readAccount({...info,owner:PublicKey.default},'Tile'));assert.throws(()=>readAccount({...info,data:Buffer.concat([data,Buffer.alloc(1)])},'Tile'));assert.throws(()=>readAccount({...info,data:Buffer.alloc(109)},'Tile'));});
