const {chromium}=require(process.env.TONARI_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict');
(async()=>{const options={headless:true,args:['--no-sandbox']};if(process.env.TONARI_CHROME_PATH)options.executablePath=process.env.TONARI_CHROME_PATH;else options.channel='chrome';const browser=await chromium.launch(options);
 try{const contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:390,height:844}}))),pages=await Promise.all(contexts.map(context=>context.newPage())),errors=[[],[]];for(const [index,page] of pages.entries()){page.on('pageerror',error=>errors[index].push(error.message));await page.addInitScript(()=>localStorage.setItem('tonari-call-latency','0'));await page.goto('http://127.0.0.1:4173/apps/web/call-response.html');await page.waitForFunction(()=>document.documentElement.dataset.offlineReady==='true'&&!document.querySelector('#rally').hidden);}
  const upload=async(target,source,name)=>{const png=await source.locator('#rally-qr').screenshot();await target.locator('#rally-image').setInputFiles({name,mimeType:'image/png',buffer:png});};
  await upload(pages[1],pages[0],'key.png');await pages[1].waitForFunction(()=>document.querySelector('#rally-status').textContent.includes('署名コールです'));
  await upload(pages[0],pages[1],'call.png');await pages[0].waitForFunction(()=>!document.querySelector('#rally-play').hidden);await pages[0].locator('#rally-play').click();await pages[0].waitForFunction(()=>document.documentElement.dataset.callPhase==='response');const sequence=await pages[0].locator('#ticker i').evaluateAll(nodes=>nodes.map(node=>Number(node.dataset.callPad))),step=30000/100;for(let index=0;index<sequence.length;index++){if(index)await pages[0].waitForTimeout(step);await pages[0].locator(`[data-pad="${sequence[index]}"]`).dispatchEvent('pointerdown');}await pages[0].waitForFunction(()=>document.querySelector('#rally-status').textContent.includes('返事に署名'));
  await upload(pages[1],pages[0],'packet.png');await pages[1].waitForFunction(()=>document.querySelector('#rally-status').textContent.includes('双方の署名'));
  await contexts[0].setOffline(true);await pages[0].reload();await pages[0].waitForFunction(()=>document.querySelector('#rally-status').textContent.includes('双方の署名')&&!document.querySelector('#rally-next').hidden);await pages[0].locator('#rally-next').click();await pages[0].waitForFunction(()=>document.querySelector('#rally-status').textContent.includes('1拍長く'));
  await upload(pages[1],pages[0],'next-call.png');await pages[1].waitForFunction(()=>!document.querySelector('#rally-play').hidden);assert.deepEqual(errors,[[],[]]);console.log(JSON.stringify({status:'PASS',two_device_signed_rally:true,qr_image_transport:true,mutual_signature:true,offline_reload:true,role_reversal:true,prior_packet_bound:true,page_errors:errors}));
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
