import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {IDBFactory} from 'fake-indexeddb';
import {createDevice,concat,fromHex} from '../packages/protocol/swap.mjs';
import {signRallyCall,inspectRallyCall,acceptRallyCall,rallyWire,RALLY_BODY_BYTES} from '../packages/protocol/rally.mjs';
import {validateCall} from '../packages/games/call-response.mjs';
import {encodeRallySession,inspectRallySession} from '../packages/protocol/rally-session.mjs';
import {publicKeyWire} from '../packages/protocol/wire-v2.mjs';
import {qrRaster,scanRaster} from '../packages/protocol/qr.mjs';
import {DeviceStore} from '../packages/protocol/storage.mjs';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const zero='00'.repeat(32),show='11'.repeat(32),rally='22'.repeat(16);
const bytes=signed=>concat(fromHex(signed.body,RALLY_BODY_BYTES),fromHex(signed.signature,64));
test('signed public rally state survives reload only for a participant',async()=>{const a=await createDevice(),b=await createDevice(),c=await createDevice(),signed=await signRallyCall(a,{show,rally,from:a.publicKey,to:b.publicKey,prior:zero,round:1,bpm:100,pads:[0,1,2]}),callWire=rallyWire('C',bytes(signed)),stored=await encodeRallySession(callWire,a.publicKey);assert.equal((await inspectRallySession(stored,b.publicKey)).type,'C');await assert.rejects(()=>inspectRallySession(stored,c.publicKey),/BAD_RALLY_SESSION/);const packet=await acceptRallyCall(b,signed,{accuracy:100,misses:0,fullCombo:true}),packetStored=await encodeRallySession(rallyWire('P',packet),b.publicKey),restored=await inspectRallySession(packetStored,a.publicKey);assert.equal(restored.type,'P');assert.equal(restored.proof.mutuallySigned,true);});
test('session rejects altered schema, wire and signature instead of trusting local storage',async()=>{const a=await createDevice(),b=await createDevice(),signed=await signRallyCall(a,{show,rally,from:a.publicKey,to:b.publicKey,prior:zero,round:1,bpm:100,pads:[0,1,2]}),wire=rallyWire('C',bytes(signed));await assert.rejects(()=>inspectRallySession('{',a.publicKey));await assert.rejects(()=>inspectRallySession(JSON.stringify({version:1,wire,extra:true}),a.publicKey));const changed=wire.slice(0,-1)+(wire.endsWith('A')?'B':'A');await assert.rejects(()=>inspectRallySession(JSON.stringify({version:1,wire:changed}),a.publicKey));});
test('dedicated rally identity namespace is admitted without widening arbitrary storage names',async()=>{globalThis.indexedDB=new IDBFactory();const root=await DeviceStore.open('call-response-rally');assert.equal(root.device.privateKey.extractable,false);root.close();await assert.rejects(()=>DeviceStore.open('call-response-rally-extra'),/BAD_NAMESPACE/);});
test('public key, signed call and mutual packet survive strict QR raster scanning',async()=>{const a=await createDevice(),b=await createDevice(),signed=await signRallyCall(a,{show,rally,from:a.publicKey,to:b.publicKey,prior:zero,round:1,bpm:100,pads:[0,1,2]}),packet=await acceptRallyCall(b,signed,{accuracy:100,misses:0,fullCombo:true});for(const wire of [publicKeyWire(a.publicKey),rallyWire('C',bytes(signed)),rallyWire('P',packet)]){const image=qrRaster(wire);assert.equal(scanRaster(image.data,image.width,image.height),wire);}});
test('an inspected rally call is normalized with finite playback timing',async()=>{const a=await createDevice(),b=await createDevice(),signed=await signRallyCall(a,{show,rally,from:a.publicKey,to:b.publicKey,prior:zero,round:1,bpm:100,pads:[0,1,2]}),rallyCall=await inspectRallyCall(signed),playable=validateCall({id:`rally-${rallyCall.round}`,bpm:rallyCall.bpm,pads:[...rallyCall.pads]});assert.equal(playable.stepMs,300);assert.equal(Number.isFinite(playable.stepMs),true);});
