import test from 'node:test';import assert from 'node:assert/strict';
import {createDevice,fromHex,concat} from '../packages/protocol/swap.mjs';
import {RALLY_BODY_BYTES,RALLY_PACKET_BYTES,encodeRallyCall,decodeRallyCall,signRallyCall,inspectRallyCall,acceptRallyCall,inspectRallyPacket,continueRally,rallyWire,readRallyWire} from '../packages/protocol/rally.mjs';
const zeros=n=>'00'.repeat(n),show='11'.repeat(32),rally='22'.repeat(16);
async function fixture(){const a=await createDevice(),b=await createDevice(),value={show,rally,from:a.publicKey,to:b.publicKey,prior:zeros(32),round:1,bpm:110,pads:[0,1,null,2]};const signed=await signRallyCall(a,value),packet=await acceptRallyCall(b,signed,{accuracy:100,misses:0,fullCombo:true});return {a,b,value,signed,packet};}
test('fixed rally call codec roundtrips rests and canonical padding',async()=>{const {value}=await fixture(),body=encodeRallyCall(value);assert.equal(body.length,RALLY_BODY_BYTES);assert.deepEqual(decodeRallyCall(body),value);const bad=body.slice();bad[175]=1;assert.throws(()=>decodeRallyCall(bad),/BAD_RALLY_PADDING/);});
test('two devices create a mutually signed offline rally handshake',async()=>{const {value,signed,packet}=await fixture();assert.deepEqual(await inspectRallyCall(signed),value);assert.equal(packet.length,RALLY_PACKET_BYTES);const result=await inspectRallyPacket(packet);assert.equal(result.mutuallySigned,true);assert.deepEqual(result.grade,{accuracy:100,misses:0,fullCombo:true});});
test('call, grade and both signatures reject every region tampering',async()=>{const {packet}=await fixture();for(const index of [10,RALLY_BODY_BYTES+5,RALLY_BODY_BYTES+64,RALLY_BODY_BYTES+67]){const bad=packet.slice();bad[index]^=1;await assert.rejects(()=>inspectRallyPacket(bad));}});
test('only the responder continues one beat longer and binds the prior packet hash',async()=>{const {a,b,packet}=await fixture();const next=await continueRally(b,packet,[0,1,2,null,3],120),call=await inspectRallyCall(next),previous=await inspectRallyPacket(packet);assert.equal(call.from,b.publicKey);assert.equal(call.to,a.publicKey);assert.equal(call.round,2);assert.equal(call.prior,previous.id);await assert.rejects(()=>continueRally(a,packet,[0,1,2,3,0],120),/WRONG_RALLY_CONTINUATION/);});
test('compact wires are exact canonical stage-bound payloads',async()=>{const {signed,packet}=await fixture(),signedBytes=concat(fromHex(signed.body,RALLY_BODY_BYTES),fromHex(signed.signature,64));for(const [type,bytes] of [['C',signedBytes],['P',packet]]){const wire=rallyWire(type,bytes),read=readRallyWire(wire);assert.equal(read.type,type);assert.deepEqual(read.bytes,bytes);assert.throws(()=>readRallyWire(wire+'='));}assert.throws(()=>rallyWire('P',signedBytes));});
test('unknown fields, self rally, bounds and dishonest grades fail closed',async()=>{const {a,b,value,signed}=await fixture();for(const bad of [{...value,extra:1},{...value,from:value.to},{...value,round:0},{...value,bpm:99},{...value,pads:[0,1]}])assert.throws(()=>encodeRallyCall(bad));await assert.rejects(()=>acceptRallyCall(b,signed,{accuracy:100,misses:1,fullCombo:false}),/BAD_RALLY_GRADE/);await assert.rejects(()=>acceptRallyCall(a,signed,{accuracy:100,misses:0,fullCombo:true}),/WRONG_RALLY_RESPONDER/);});
