import {fromHex,hex,concat,digest} from './swap.mjs';
const MAGIC=new Uint8Array([84,79,78,67,65,76,76,1]),ACCEPT=new TextEncoder().encode('TONARI/v1/rally-accept\0');
export const RALLY_BODY_BYTES=176,RALLY_SIGNED_BYTES=240,RALLY_PACKET_BYTES=307;
const fields=['show','rally','from','to','prior','round','bpm','pads'];
const fail=code=>{throw Error(code);};
const exact=(value,keys,code)=>{if(!value||Object.getPrototypeOf(value)!==Object.prototype||Object.keys(value).sort().join()!==keys.slice().sort().join())fail(code);};
const byte=(value,code)=>{if(!Number.isInteger(value)||value<0||value>255)fail(code);return value;};

export function encodeRallyCall(value){
 exact(value,fields,'BAD_RALLY_FIELDS');if(!Number.isInteger(value.round)||value.round<1||value.round>64||!Number.isInteger(value.bpm)||value.bpm<100||value.bpm>140||!Array.isArray(value.pads)||value.pads.length<3||value.pads.length>12||value.pads.some(x=>x!==null&&(!Number.isInteger(x)||x<0||x>3))||value.from===value.to)fail('BAD_RALLY_CALL');
 const out=new Uint8Array(RALLY_BODY_BYTES);out.set(MAGIC);let pos=8;out.set(fromHex(value.show,32),pos);pos+=32;out.set(fromHex(value.rally,16),pos);pos+=16;for(const key of ['from','to','prior']){out.set(fromHex(value[key],32),pos);pos+=32;}out[pos++]=value.round;out[pos++]=value.bpm;out[pos++]=value.pads.length;for(let index=0;index<12;index++)out[pos++]=index<value.pads.length?(value.pads[index]??255):254;return out;
}
export function decodeRallyCall(bytes){
 if(!(bytes instanceof Uint8Array)||bytes.length!==RALLY_BODY_BYTES||!MAGIC.every((x,i)=>bytes[i]===x))fail('BAD_RALLY_BODY');let pos=8;const value={show:hex(bytes.slice(pos,pos+32))};pos+=32;value.rally=hex(bytes.slice(pos,pos+16));pos+=16;for(const key of ['from','to','prior']){value[key]=hex(bytes.slice(pos,pos+32));pos+=32;}value.round=bytes[pos++];value.bpm=bytes[pos++];const count=bytes[pos++];value.pads=[];for(let index=0;index<12;index++){const pad=bytes[pos++];if(index<count)value.pads.push(pad===255?null:pad);else if(pad!==254)fail('BAD_RALLY_PADDING');}if(bytes.slice(pos).some(Boolean))fail('BAD_RALLY_PADDING');encodeRallyCall(value);return value;
}
async function verify(publicKey,signature,message){const key=await crypto.subtle.importKey('raw',fromHex(publicKey,32),'Ed25519',false,['verify']);return crypto.subtle.verify('Ed25519',key,signature,message);}
export async function signRallyCall(device,value){const body=encodeRallyCall(value);if(device.publicKey!==value.from)fail('WRONG_RALLY_MAKER');return {body:hex(body),signature:hex(new Uint8Array(await crypto.subtle.sign('Ed25519',device.privateKey,body)))};}
export async function inspectRallyCall(signed){exact(signed,['body','signature'],'BAD_RALLY_ENVELOPE');const body=fromHex(signed.body,RALLY_BODY_BYTES),signature=fromHex(signed.signature,64),call=decodeRallyCall(body);if(!await verify(call.from,signature,body))fail('BAD_RALLY_CALL_SIGNATURE');return call;}
function gradeBytes(grade){exact(grade,['accuracy','misses','fullCombo'],'BAD_RALLY_GRADE');const accuracy=byte(grade.accuracy,'BAD_RALLY_GRADE'),misses=byte(grade.misses,'BAD_RALLY_GRADE');if(accuracy>100||(grade.fullCombo!==true&&grade.fullCombo!==false)||(grade.fullCombo?(accuracy!==100||misses!==0):(accuracy===100||misses===0)))fail('BAD_RALLY_GRADE');return new Uint8Array([accuracy,misses,grade.fullCombo?1:0]);}
export async function acceptRallyCall(device,signed,grade){const call=await inspectRallyCall(signed);if(device.publicKey!==call.to)fail('WRONG_RALLY_RESPONDER');const body=fromHex(signed.body,RALLY_BODY_BYTES),signature=fromHex(signed.signature,64),g=gradeBytes(grade),message=concat(ACCEPT,await digest(body),signature,g),reply=new Uint8Array(await crypto.subtle.sign('Ed25519',device.privateKey,message));return concat(body,signature,g,reply);}
export async function inspectRallyPacket(packet){if(!(packet instanceof Uint8Array)||packet.length!==RALLY_PACKET_BYTES)fail('BAD_RALLY_PACKET');const snapshot=packet.slice(),body=snapshot.slice(0,RALLY_BODY_BYTES),signature=snapshot.slice(RALLY_BODY_BYTES,RALLY_SIGNED_BYTES),g=snapshot.slice(RALLY_SIGNED_BYTES,RALLY_SIGNED_BYTES+3),reply=snapshot.slice(RALLY_SIGNED_BYTES+3),call=decodeRallyCall(body),grade={accuracy:g[0],misses:g[1],fullCombo:g[2]===1};gradeBytes(grade);if(!await verify(call.from,signature,body))fail('BAD_RALLY_CALL_SIGNATURE');if(!await verify(call.to,reply,concat(ACCEPT,await digest(body),signature,g)))fail('BAD_RALLY_ACCEPT_SIGNATURE');return {call,grade,id:hex(await digest(snapshot)),mutuallySigned:true};}
export async function continueRally(device,packet,pads,bpm){const prior=await inspectRallyPacket(packet);if(device.publicKey!==prior.call.to)fail('WRONG_RALLY_CONTINUATION');return signRallyCall(device,{show:prior.call.show,rally:prior.call.rally,from:prior.call.to,to:prior.call.from,prior:prior.id,round:prior.call.round+1,bpm,pads});}

const sizes={C:RALLY_SIGNED_BYTES,P:RALLY_PACKET_BYTES},prefix=type=>`TONARIC1:${type}:`;
const b64=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export function rallyWire(type,bytes){if(!Object.hasOwn(sizes,type)||!(bytes instanceof Uint8Array)||bytes.length!==sizes[type])fail('BAD_RALLY_WIRE');return prefix(type)+b64(bytes);}
export function readRallyWire(text){if(typeof text!=='string'||text.length>430)fail('BAD_RALLY_WIRE');const match=/^TONARIC1:([CP]):([A-Za-z0-9_-]+)$/.exec(text);if(!match)fail('BAD_RALLY_WIRE');const size=sizes[match[1]],encoded=match[2];if(encoded.length!==Math.ceil(size*8/6))fail('BAD_RALLY_WIRE');let bytes;try{bytes=Uint8Array.from(atob(encoded.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-encoded.length%4)%4)),x=>x.charCodeAt(0));}catch{fail('BAD_RALLY_WIRE');}if(bytes.length!==size||b64(bytes)!==encoded)fail('BAD_RALLY_WIRE');return {type:match[1],bytes};}
